### DISCUSSION TITLE
Welcome to eodash Discussions!

### DISCUSSION THREAD

**Discussion by A-Behairi** [eodash/eodash#25] [Announcements]
## 👋 Welcome!
  We’re using Discussions as a place to connect with other members of our community. We hope that you:
  * Ask questions you’re wondering about.
  * Share ideas.
  * Engage with other community members.
  * Welcome others and are open-minded. Remember that this is a community we
  build together 💪.

  To get started, comment below with an introduction of yourself and tell us about what you do with this community.

**Comment by axstgmv** [comment]
Hello!
I'm trying to create my own eodash instance using this repository:  https://github.com/eodash/eodash-instance-template
I have successfully created an eodash-catalog in which I added Colorlegend to one of my collections:

```
Colorlegend:
  title: Legend
  range: ["#ffffb2","#fecc5c","#fd8d3c","#f03b20","#bd0026"]
  domain: [100, 500]
  tickFormat: .0f
  tickValues: [100, 300, 500]
```

In main.js file in the frontend app I'm using EodashLayerControl, specifying "legend" in properties.tools, but there is no legend in the LayerControl UI and the opacity slider is still visible, even though it's not listed in the `tools` array.

```
{
        id: Symbol(),
        type: "internal",
        title: "Layer Control",
        layout: { x: 0, y: 8, w: 5, h: 4 },
        widget: {
          name: "EodashLayerControl",
          properties: {
            tools: () => ["legend"],
          },
        },
      },
```
![image](https://github.com/user-attachments/assets/b03f7c24-c23a-480c-947a-a845921776fa)

Any suggestions would be appreciated, thank you!
